version: 0.0
os: linux
files:
  - source: /
    destination: /www/projects/wa-api/current
overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/app_start.sh
      runas: ubuntu
